# Generated by Django 4.2.7 on 2025-05-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_add_artist_album_ids_to_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='album_id',
            field=models.BigIntegerField(blank=True, help_text='专辑ID（来自第三方API）', null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='artist_id',
            field=models.BigIntegerField(blank=True, help_text='歌手ID（来自第三方API）', null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='song_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
