# Generated by Django 4.2.7 on 2025-05-26 06:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SearchHistory",
        ),
    ]
